# Generated by Django 3.2.9 on 2021-11-18 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcionmenu',
            name='contador',
            field=models.IntegerField(default=0, verbose_name='Cantidad de Veces Adquirido'),
        ),
    ]
