# Generated by Django 3.2.9 on 2021-11-19 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_opcionmenu_contador'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcionmenu',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='static/img'),
        ),
    ]
