# Generated by Django 3.2.9 on 2021-11-19 19:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_opcionmenu_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 19, 13, 12, 30, 127999), verbose_name='Fecha'),
        ),
    ]
