# Generated by Django 3.2.9 on 2021-11-30 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20211129_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcionmenu',
            name='top',
            field=models.IntegerField(default=1, verbose_name='Cantidad de Toppings'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orden',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 30, 10, 46, 16, 404073), verbose_name='Fecha'),
        ),
    ]
