# Generated by Django 3.2.9 on 2021-12-01 21:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20211130_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 1, 15, 49, 32, 963711), verbose_name='Fecha'),
        ),
    ]
